/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dd1b05d2-3f9d-4e4f-b1e5-2b3b4339be52",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_y1Oh82Whf",
    "aws_user_pools_web_client_id": "7k0ek4fctieihjr3t1pm7j70ht",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mno2xralxfe2xo7lccejvmwda4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
